config/routes.rb
Rails.application.routes.draw do
  resources :lists
  
  get 'destinations/show'

  get 'destinations/edit'

  get 'lists/index'

  get 'lists/show'

  get 'lists/new'

  get 'lists/edit'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/destination.rb
class Destination < ApplicationRecord
  belongs_to :list
end

app/models/list.rb
class List < ApplicationRecord
  has_one :destination
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/destinations_controller.rb
class DestinationsController < ApplicationController
  def show
  end

  def edit
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
  end

  def new
    @list = List.new
  end

  def edit
    @list = List.find(params[:id])
  end
  def destroy
    @list = List.find(params[:id])
    @list.destroy
    redirect_to lists_path
  end
  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to lists_path
    else
      render :new
    end
  end

  def update
    @list =List.find(params[:id])
    if @list.update(list_params)
      redirect_to @list
    else
      render 'edit'
    end
  end
  private
    def list_params
      params.require(:list).permit(:name, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/destinations_helper.rb
module DestinationsHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/destinations/edit.html.erb
<h1>Destinations#edit</h1>
<p>Find me in app/views/destinations/edit.html.erb</p>

app/views/destinations/show.html.erb
<h1>Destinations#show</h1>
<p>Find me in app/views/destinations/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ActivityList</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/edit.html.erb
<h1>Edit List</h1>
<%= form_with(model: @list) do |form| %>
  <p>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </p>
  <p>
    <%= form.label :description %><br>
    <%= form.text_field :description %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>
<p>Find me in app/views/lists/edit.html.erb</p>

app/views/lists/index.html.erb
<h1>Lists</h1>
<%= link_to 'New List', new_list_path %>
<% @lists.each do |list|  %>
    <h2><%= list.name %></h2>
    <%= link_to 'Show', list_path(list) %>
    <%= link_to 'Edit', edit_list_path(list) %>
    <%= link_to 'Destroy', list_path(list),
        method: :delete,
        data: {confirm: 'Are you sure?'} %>
<% end %>
<p>Find me in app/views/lists/index.html.erb</p>

app/views/lists/new.html.erb
<h1>Create List</h1>
<%= form_for @list do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>
    <%= f.submit %>
<% end %>
<p>Find me in app/views/lists/new.html.erb</p>

app/views/lists/show.html.erb
<h1><%= @list.name %></h1>
<p><%= @list.description %></p>
<%= link_to 'Edit', edit_list_path(@list) %>
<%= link_to 'Menu', lists_path %>